### PR TITLE
Small Link revamp

### PR DESCRIPTION
**Pull request by fangmarks**

### CODE REVIEW

**Review by fangmarks — COMMENTED** [review]
Since this List is still edited mostly by Hand, I figured it'd be easier to make the Bot Name Link just the Brackets instead of a full markdown link

**Review by WaviestBalloon — CHANGES_REQUESTED** [review]
I don't really think it would be helpful removing the hyperlinks from any keyword of "Discord Server", not many people scroll all the way down, just a suggestion. I'd think it'd be better to keep the Discord invite links where they were originally at.

**Review by Gideon-Foxo — APPROVED** [review]

**Comment by fangmarks** [comment]
@WaviestBalloon I didn't move anything. The way it works now is that you only have to put `[Discord Server]` instead of the whole `[title](link)` thing. The Links at the bottom don't show up

**Comment by WaviestBalloon** [comment]
You learn something new everyday

**Pull request merged**
